# Site settings
author: Geoff Elliott
title: Code Gray
header-img: img/home-bg.png
email: tinywv@gmail.com
copyright_name: Geoff Elliott
description: > # this means to ignore newlines until "baseurl:"
  Jumping into the tech world late in life!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  geoffwv

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
